## Inverse Matrix

The inverse of a matrix A is another matrix A<sup>-1</sup> (pronounced "A inverse") that multiplies A to produce the identity matrix. In other words, A<sup>-1</sup>A = I

This is how one can "cancel" a matrix

We need to "cancel" a matrix in order to solve problems that can be expressed in the form Ax=b, where A and b are known quantities and we want to solve for x \
To solve these expressions: x = A<sup>-1</sup>b

The inverse of a matrix is always unique

In [2]:
import numpy as np
from matplotlib import pyplot as plt

There are three different kind of inverses that have different conditions for invertibility:
- full inverse: to have a full-inverse, a matrix must be <i>squared</i> and <i>full-rank</i>
- one-sided: can transform a rectangular matrix into an identity matrix, but it works only for one multiplication order. A tall matrix T can have a left-inverse (LT = I, but TL != I). Likewise, a short and wide matrix has a right-inverse.
- pseudoinverse: every matrix has a pseudoinverse, regardless of its shape and rank. Matrices that do not have a full or a one-side inverse are "singular" or "non-invertible". A reduced-rank matrix is always singular

In [3]:
A = np.array([[1,2,3],[4,5,6], [7,7,7]])

# check if A is singular
# in this case trying to calculate the inverse matrix will raise a "singular matrix" error, because the matrix has 0 determinant
print(np.linalg.det(A))

# let's take now a squared full rank matrix (which is not singular):
A = np.array([[1,2,3],[4,5,6], [7,7,9]])
print(np.linalg.det(A))

Ainv = np.linalg.inv(A)
print(Ainv)
print(np.abs(np.rint(Ainv@A)))

0.0
-5.999999999999997
[[-0.5        -0.5         0.5       ]
 [-1.          2.         -1.        ]
 [ 1.16666667 -1.16666667  0.5       ]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### One-Sided Inverse

For a matrix T of side M>N (a "tall" matrix) there is no tall matrix T<sup>-1</sup> such as T<sup>-1</sup>T=I

But there is a "large" matrix L such as LT=I. Here is how to find it:

T = tall matrix
Tt = T transposed

TtT = T transposed multiply T \
(TtT)<sup>-1</sup> = TtT inverse

(TtT)<sup>-1</sup> multiply TtT is equal to I \
so (TtT)<sup>-1</sup>(TtT)=I

We than understand that:
L = (TtT)<sup>-1</sup>T<sup>T</sup>

so that LT = I

L is called left-inverse of matrix T

Left-inverse is an important concept in machine learning when it comes to fitting statistical models to data

Left-inverse is defined only for tall matrices that have full column rank

In [4]:
# Let's demonstrate that a tall matrix times its transpose has a full inverse:
T = np.random.randint(-10,11,size=(40,4))
TtT = T.T@T
TtT_inv = np.linalg.inv(TtT)
print(np.abs(np.rint(TtT_inv@TtT)))

# now let's calculate L (left-inverse) matrix
L = TtT_inv @ T.T 
print(np.abs(np.rint(L@T)))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


## Moore-Penrose Pseudoinverse

A reduced-rank matrix has no inverse. But it is possible to calculate a pseudo-inverse (called Moore-Penrose pseudoinverse). \
Pseudoinverse are tranformation that bring matrices close to the identity matrix. \

The algorithm behind pseudo-inversion is related to SVD and will be studied later

In [9]:
M = np.array([[1,4],[2,8]])

print('trying to calculate inverse:')
try:
    np.linalg.inv(M)
except Exception as e:
    print('Error: ' + str(e))

print('calculate pseudo-inverse instead: ')
print(np.linalg.pinv(M))


trying to calculate inverse:
Error: Singular matrix
calculate pseudo-inverse instead: 
[[0.01176471 0.02352941]
 [0.04705882 0.09411765]]


### Other notes on matrices

The determinant of a matrix can be numerically unstable, and therefore computing many determinants on large matrices can lead to numerical inaccurancies. \
As inverting a matrix involves determinant calculation, many libraries strive to avoid explicitly inverting matrices. \
Matrices that have numerical values in roughly the same range (the condition number, difference between highest and lower value of a matrix), tend to be more stable (but this is not guaranteed) 

The geometric interpretation of matrix inverse is "undoing" the matrix transformation. This is why it is not possible to calculate the inverse of a reduced-rank matrix: one it goes "flat" (0 determinant), it is not possible to "rebuild" the original matrix
