# MATRIX

<div>
<img src="images/02_Matrix/01_Matrix_.jpg" width="500"/>
</div>

In [ ]:
import numpy as np
from matplotlib import pyplot as plt

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

def show_matrix_as_image(matrix, title='Matrix as Image'):
    fig, ax = plt.subplots(figsize=(4,4))
    plt.imshow(matrix, cmap='gray', interpolation='nearest')
    plt.colorbar()
    plt.title(title)
    plt.xlabel('Columns')
    plt.ylabel('Rows')
    plt.show()

# Example matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Display the matrix as an image
show_matrix_as_image(matrix)

# create an example of a large matrix filled with random numbers
matrix = np.random.rand(2000, 2000)

# Display the matrix as an image
show_matrix_as_image(matrix)

## Special matrices are the identity matrix (equivalent of a scalar 1) and the zero matrix

In [ ]:
identity = np.eye(5)
zero = np.zeros([5,5])
print(identity)
print(zero)

show_matrix_as_image(identity, 'Identity Matrix')

## Matrix Math: addition, scalar multiplication, Hadamard multiplication

<div>
<img src="images/02_Matrix/matrix_math.jpg" width="500"/>
</div>



In [ ]:
M1 = np.array([[2,3,4],[1,2,4]]) 
M2 = np.array([[0,3,1],[-1,-4,2]])

# adding two matrices 
print(M1 + M2)

# adding a scalar is possible in Python thanks to broadcasting, but it's not a formal linear algebra operation
M1 = np.array([[4,5,1], [0,1,11], [4,9,7]])

ʎ = 6
print(ʎ+M1)

# there is instead a linear-algebra way to add a scalar to a square matrix, that is called "shifting", which is adding a scalar to an identity matrix, then add it.$
# in this case, only the diagonal element change. It's an important operation used to fit a model to data in ML
id = np.eye(len(M1))
print(M1 + (id*6))

# element-wise (Hadamard) multiplication
M1 = np.array([[2,3,4],[1,2,4]]) 
M2 = np.array([[0,3,1],[-1,-4,2]])
print(M1*M2)

## Standard Matrix Multiplication

<div>
<img src="images/02_Matrix/matrix_mult_1.jpg" width="500"/>
</div>


<div>
<img src="images/02_Matrix/matrix_mult_2.jpg" width="500"/>
</div>



In [ ]:
M1 = np.array([[1,2,4], [4,5,6]])
M2 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

standard_mult = M1@M2
print(standard_mult)

# Linear Weighted Combination can be done with a vector-matrix multiplication

M = np.array([[2,3], [2,1]])
x = np.array([3,4.5])

print(M@x)

# When we think of a vector as a geometric line, then matrix-vector multiplication becomes a way of rotating and scaling the vector
v = np.array([3,4])
M = np.array([[2,0],[0,-1]])

transformed_v = v@M
print(transformed_v)

fig, ax = plt.subplots()
plt.xlim(-2,8)
plt.ylim(-6,5)
ax = plt.gca()
ax.set_aspect('equal', adjustable='box')
plt.grid()

plt.plot([0,v[0]],[0, v[1]],color='rosybrown', label='original vector')
plt.plot([0,transformed_v[0]],[0, transformed_v[1]],color='red', label='rotated and scaled vector')


plt.legend()
plt.show()

## Transpose and LIVE EVIL

In [35]:
# transpose a matrix with Python can be done in different ways:
M = np.array([[2,3,4], [6,7,8]])
print(M.T)
print(M.transpose())

# to remember the order of evaluation of transposed matrices, we can use the mnemonic phrase LIVE EVIL
L = np.array([[2,3], [4,5]])
I = np.array([[4,5],[7,9]])
V = np.array([[9,8],[10,22]])
E = np.array([[5,6], [9,6]])

print((L@I@V@E).T)
print(E.T @ V.T @ I.T @ L.T)

[[2 6]
 [3 7]
 [4 8]]
[[2 6]
 [3 7]
 [4 8]]
[[12569 22087]
 [10062 17682]]
[[12569 22087]
 [10062 17682]]
