## QR and LU decomposition

### Orthogonal matrices
The letter Q is often used to indicate orthogonal matrices\
Orthogonal matrices have two properties:
- orthogonal columns: all columns are pair-wise orthogonal
- unit-norm columns: the norm (geometric length) of each column is exactly 1

That means that the dot product of a column with itself is equal to 1, and the dot product of a column with another column is 0

The matrix equation expressing the two key properties of an orthogonal matrix is simply marvelous:

Q<sup>T</sup>Q = I

This is a big deal, because a matrix that multiply another matrix giving as a result the identity matrix is the definition of inverse! That means that the inverse of an orthogonal matrix is its transpose.

Examples of orthogonal matrices are: the identity matrix itself, the rotation matrix, permutation matrices, and a lot of others, as long as they have the two properties previously mentioned

In [23]:
import numpy as np

In [24]:
def roundAbs(matrix):
    return np.abs(np.rint(matrix))

In [31]:
rot_90 = np.array([[0,-1], [1,0]])
rot_180 = np.array([[-1,0],[0,-1]])
rot_270 = np.array([[0,1],[-1,0]])

row_perm = np.array([[0,0,1,0],[0,1,0,0],[0,0,0,1],[1,0,0,0]])
col_perm = np.array([[0,0,0,1],[0,1,0,0],[1,0,0,0],[0,0,1,0]])

print(rot_90.T@rot_90)
print(rot_180.T@rot_180)
print(rot_270@rot_270.T)

print(row_perm.T@row_perm)
print(col_perm.T@col_perm)

ʎ = 1 / np.sqrt(2)
A = ʎ * np.array([[1,-1],[1,1]])
print(roundAbs(A.T@A))

ʎ = 1 / 3
A = ʎ * np.array([[1,2,2],[2,1,-2],[-2,2,1]])
print(roundAbs(A.T@A))








[[1 0]
 [0 1]]
[[1 0]
 [0 1]]
[[1 0]
 [0 1]]
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]
[[1. 0.]
 [0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
